import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/ReactToastify.min.css';
import NavBar from "@/components/NavBar";
import WalletWrapper from "@/app/context/WalletContextWrapper";
import { getUserData } from "@/app/actions/getUserData";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserData(); // This will redirect if not authenticated

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <WalletWrapper>
          <NavBar userEmail={user.email} />
          {children}
          <ToastContainer
            position="bottom-left"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </WalletWrapper>
      </body>
    </html>
  );
}
